[package]
name = "thor"
description = "MQTT TLS proxy"
authors = ["Esteban Gimbernat"]
repository = "https://gitlab.com/egimbernatI/thor"
license = "MIT"
version = "0.9.3"
readme = "README.md"
edition = "2021"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[dependencies]
anyhow = "1.0.58"
custom_error = "1.9.2"
tracing = "0.1.35"
tracing-subscriber = "0.3.15"
tracing-futures = "0.2.5"
futures = "0.3.21"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_derive = "1.0.140"
serde_json = "1.0.82"
signal-hook = {version = "0.3.14", features = ["extended-siginfo"] }
chrono = "0.4.19"

tokio = { version = "1.20.0", features = ["full"] }
tokio-openssl = "0.6.3"
openssl = "0.10.41"
openssl-sys = "0.9.75"
mqtt-protocol = "0.11.2"
base64 = "0.13.0"
clap = {version = "3.1.14", features = ["derive", "cargo"] }
config = "0.13.1"
toml = "0.5.9"

[dev-dependencies]
rustls-pemfile = "1.0.0"